server:
   port: 9900

spring:
   application:
      name: api-gateway
   cloud:
      gateway:
         server:
            webflux:
               routes:
               -  id: inventory-service
                  uri: http://localhost:8082 # ✅ service discovery version
                  predicates:
                  - Path=/api/v1/inventory/**

               -  id: user-service
                  uri: http://localhost:8081 # ✅ service discovery version
                  predicates:
                  - Path=/api/users**