server:
  port: 9900

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/products/**,/api/categories/**
             
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              

            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/api/cart/**
              

  management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
