server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false  # Server doesn’t register itself
    fetch-registry: false        # Server doesn’t fetch registry
  server:
    wait-time-in-ms-when-sync-empty: 0

